// This file is automatically generated from your CSS. Any edits will be overwritten.
export const label: string;
export const point: string;
export const selected: string;
export const marked: string;
export const track: string;
